SoC Advanced: GPIO_Exported_Functions_Group1
GPIO_Exported_Functions_Group1
STM32F4xx_HAL_Driver » GPIO » GPIO_Exported_Functions
Functions
void HAL_GPIO_Init (GPIO_TypeDef *GPIOx, GPIO_InitTypeDef *GPIO_Init)
void HAL_GPIO_DeInit (GPIO_TypeDef *GPIOx, uint32_t GPIO_Pin)
Detailed Description
Function Documentation
HAL_GPIO_DeInit()
void HAL_GPIO_DeInit (GPIO_TypeDef * GPIOx, uint32_t GPIO_Pin)
Referenced by HAL_TIM_IC_MspDeInit(), and HAL_UART_MspDeInit().
HAL_GPIO_Init()
void HAL_GPIO_Init (GPIO_TypeDef * GPIOx, GPIO_InitTypeDef * GPIO_Init)
Referenced by HAL_TIM_IC_MspInit(), HAL_UART_MspInit(), and MX_GPIO_Init().