SoC Advanced: GPIO_Exported_Functions_Group2
GPIO_Exported_Functions_Group2
STM32F4xx_HAL_Driver » GPIO » GPIO_Exported_Functions
Functions
GPIO_PinState HAL_GPIO_ReadPin (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
void HAL_GPIO_WritePin (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, GPIO_PinState PinState)
void HAL_GPIO_TogglePin (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
HAL_StatusTypeDef HAL_GPIO_LockPin (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
void HAL_GPIO_EXTI_IRQHandler (uint16_t GPIO_Pin)
void HAL_GPIO_EXTI_Callback (uint16_t GPIO_Pin)
Callback function to capture changes on Push Button line and IR sensor line for Eye blinking tracking.
Detailed Description
Function Documentation
HAL_GPIO_EXTI_Callback()
void HAL_GPIO_EXTI_Callback (uint16_t GPIO_Pin)
Callback function to capture changes on Push Button line and IR sensor line for Eye blinking tracking.
Parameters
[in] GPIO_Pin Pin that triggered the Callback function.
Return values
None.
Definition at line 757 of file main.c.
{
     if (GPIO_Pin == GPIO_PIN_13) {
         if (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13) == GPIO_PIN_RESET) {
             if (is_ignition_on == false) {
                 turn_ignition_on();
             } else {
                 turn_vehicle_off();
             }
         }
     }
     if (GPIO_Pin == GPIO_PIN_7) {
         if (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_7) == GPIO_PIN_RESET) {
             twoSec = 0;
             is_sleep_detected = true;
         } else if (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_7) == GPIO_PIN_SET) {
             if (twoSec > 2000) {
                 is_sleep_detected = true;
             } else {
                 is_sleep_detected = false;
             }
         }
     }
 }
References GPIO_PIN_13, GPIO_PIN_7, GPIO_PIN_RESET, GPIO_PIN_SET, GPIOC, HAL_GPIO_ReadPin(), is_ignition_on, is_sleep_detected, turn_ignition_on(), turn_vehicle_off(), and twoSec.
HAL_GPIO_EXTI_IRQHandler()
void HAL_GPIO_EXTI_IRQHandler (uint16_t GPIO_Pin)
Referenced by EXTI15_10_IRQHandler(), and EXTI9_5_IRQHandler().
HAL_GPIO_LockPin()
HAL_StatusTypeDef HAL_GPIO_LockPin (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
HAL_GPIO_ReadPin()
GPIO_PinState HAL_GPIO_ReadPin (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Referenced by check_alcohol_level(), and HAL_GPIO_EXTI_Callback().
HAL_GPIO_TogglePin()
void HAL_GPIO_TogglePin (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
HAL_GPIO_WritePin()
void HAL_GPIO_WritePin (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin, GPIO_PinState PinState)
Referenced by check_distance_status(), driver_asleep(), MX_GPIO_Init(), start_measurement(), and turn_ignition_off().