SoC Advanced: HAL Control functions
HAL Control functions
STM32F4xx_HAL_Driver » HAL » HAL Exported Functions
HAL Control functions.
Functions
void HAL_IncTick (void)
This function is called to increment a global variable "uwTick" used as application time base.
void HAL_Delay (uint32_t Delay)
This function provides minimum delay (in milliseconds) based on variable incremented.
uint32_t HAL_GetTick (void)
Provides a tick value in millisecond.
uint32_t HAL_GetTickPrio (void)
This function returns a tick priority.
HAL_StatusTypeDef HAL_SetTickFreq (HAL_TickFreqTypeDef Freq)
Set new tick Freq.
HAL_TickFreqTypeDef HAL_GetTickFreq (void)
Return tick frequency.
void HAL_SuspendTick (void)
Suspend Tick increment.
void HAL_ResumeTick (void)
Resume Tick increment.
uint32_t HAL_GetHalVersion (void)
Returns the HAL revision.
uint32_t HAL_GetREVID (void)
Returns the device revision identifier.
uint32_t HAL_GetDEVID (void)
Returns the device identifier.
void HAL_DBGMCU_EnableDBGSleepMode (void)
Enable the Debug Module during SLEEP mode.
void HAL_DBGMCU_DisableDBGSleepMode (void)
Disable the Debug Module during SLEEP mode.
void HAL_DBGMCU_EnableDBGStopMode (void)
Enable the Debug Module during STOP mode.
void HAL_DBGMCU_DisableDBGStopMode (void)
Disable the Debug Module during STOP mode.
void HAL_DBGMCU_EnableDBGStandbyMode (void)
Enable the Debug Module during STANDBY mode.
void HAL_DBGMCU_DisableDBGStandbyMode (void)
Disable the Debug Module during STANDBY mode.
void HAL_EnableCompensationCell (void)
Enables the I/O Compensation Cell.
void HAL_DisableCompensationCell (void)
Power-down the I/O Compensation Cell.
uint32_t HAL_GetUIDw0 (void)
Returns first word of the unique device identifier (UID based on 96 bits)
uint32_t HAL_GetUIDw1 (void)
Returns second word of the unique device identifier (UID based on 96 bits)
uint32_t HAL_GetUIDw2 (void)
Returns third word of the unique device identifier (UID based on 96 bits)
Detailed Description
HAL Control functions.
 ===============================================================================
                      ##### HAL Control functions #####
 ===============================================================================
    [..]  This section provides functions allowing to:
      (+) Provide a tick value in millisecond
      (+) Provide a blocking delay in millisecond
      (+) Suspend the time base source interrupt
      (+) Resume the time base source interrupt
      (+) Get the HAL API driver version
      (+) Get the device identifier
      (+) Get the device revision identifier
      (+) Enable/Disable Debug module during SLEEP mode
      (+) Enable/Disable Debug module during STOP mode
      (+) Enable/Disable Debug module during STANDBY mode
Function Documentation
HAL_DBGMCU_DisableDBGSleepMode()
void HAL_DBGMCU_DisableDBGSleepMode (void)
Disable the Debug Module during SLEEP mode.
Return values
None
Definition at line 477 of file stm32f4xx_hal.c.
 {
   CLEAR_BIT(DBGMCU->CR, DBGMCU_CR_DBG_SLEEP);
 }
References CLEAR_BIT, DBGMCU, and DBGMCU_CR_DBG_SLEEP.
HAL_DBGMCU_DisableDBGStandbyMode()
void HAL_DBGMCU_DisableDBGStandbyMode (void)
Disable the Debug Module during STANDBY mode.
Return values
None
Definition at line 513 of file stm32f4xx_hal.c.
 {
   CLEAR_BIT(DBGMCU->CR, DBGMCU_CR_DBG_STANDBY);
 }
References CLEAR_BIT, DBGMCU, and DBGMCU_CR_DBG_STANDBY.
HAL_DBGMCU_DisableDBGStopMode()
void HAL_DBGMCU_DisableDBGStopMode (void)
Disable the Debug Module during STOP mode.
Return values
None
Definition at line 495 of file stm32f4xx_hal.c.
 {
   CLEAR_BIT(DBGMCU->CR, DBGMCU_CR_DBG_STOP);
 }
References CLEAR_BIT, DBGMCU, and DBGMCU_CR_DBG_STOP.
HAL_DBGMCU_EnableDBGSleepMode()
void HAL_DBGMCU_EnableDBGSleepMode (void)
Enable the Debug Module during SLEEP mode.
Return values
None
Definition at line 468 of file stm32f4xx_hal.c.
 {
   SET_BIT(DBGMCU->CR, DBGMCU_CR_DBG_SLEEP);
 }
References DBGMCU, DBGMCU_CR_DBG_SLEEP, and SET_BIT.
HAL_DBGMCU_EnableDBGStandbyMode()
void HAL_DBGMCU_EnableDBGStandbyMode (void)
Enable the Debug Module during STANDBY mode.
Return values
None
Definition at line 504 of file stm32f4xx_hal.c.
 {
   SET_BIT(DBGMCU->CR, DBGMCU_CR_DBG_STANDBY);
 }
References DBGMCU, DBGMCU_CR_DBG_STANDBY, and SET_BIT.
HAL_DBGMCU_EnableDBGStopMode()
void HAL_DBGMCU_EnableDBGStopMode (void)
Enable the Debug Module during STOP mode.
Return values
None
Definition at line 486 of file stm32f4xx_hal.c.
 {
   SET_BIT(DBGMCU->CR, DBGMCU_CR_DBG_STOP);
 }
References DBGMCU, DBGMCU_CR_DBG_STOP, and SET_BIT.
HAL_Delay()
__weak void HAL_Delay (uint32_t Delay)
This function provides minimum delay (in milliseconds) based on variable incremented.
Note
In the default implementation , SysTick timer is the source of time base. It is used to generate interrupts at regular time intervals where uwTick is incremented.
This function is declared as __weak to be overwritten in case of other implementations in user file.
Parameters
Delay specifies the delay time length, in milliseconds.
Return values
None
Definition at line 389 of file stm32f4xx_hal.c.
 {
   uint32_t tickstart = HAL_GetTick();
   uint32_t wait = Delay;
   /* Add a freq to guarantee minimum wait */
   if (wait < HAL_MAX_DELAY)
   {
     wait += (uint32_t)(uwTickFreq);
   }
   while((HAL_GetTick() - tickstart) < wait)
   {
   }
 }
References HAL_GetTick(), HAL_MAX_DELAY, and uwTickFreq.
Referenced by check_alcohol_level(), check_distance_status(), and driver_asleep().
HAL_DisableCompensationCell()
void HAL_DisableCompensationCell (void)
Power-down the I/O Compensation Cell.
Note
The I/O compensation cell can be used only when the device supply voltage ranges from 2.4 to 3.6 V.
Return values
None
Definition at line 535 of file stm32f4xx_hal.c.
 {
   *(__IO uint32_t *)CMPCR_CMP_PD_BB = (uint32_t)DISABLE;
 }
References __IO, CMPCR_CMP_PD_BB, and DISABLE.
HAL_EnableCompensationCell()
void HAL_EnableCompensationCell (void)
Enables the I/O Compensation Cell.
Note
The I/O compensation cell can be used only when the device supply voltage ranges from 2.4 to 3.6 V.
Return values
None
Definition at line 524 of file stm32f4xx_hal.c.
 {
   *(__IO uint32_t *)CMPCR_CMP_PD_BB = (uint32_t)ENABLE;
 }
References __IO, CMPCR_CMP_PD_BB, and ENABLE.
HAL_GetDEVID()
uint32_t HAL_GetDEVID (void)
Returns the device identifier.
Return values
Device identifier
Definition at line 459 of file stm32f4xx_hal.c.
 {
   return((DBGMCU->IDCODE) & IDCODE_DEVID_MASK);
 }
References DBGMCU, and IDCODE_DEVID_MASK.
HAL_GetHalVersion()
uint32_t HAL_GetHalVersion (void)
Returns the HAL revision.
Return values
version : 0xXYZR (8bits for each decimal, R for RC)
Definition at line 441 of file stm32f4xx_hal.c.
 {
   return __STM32F4xx_HAL_VERSION;
 }
References __STM32F4xx_HAL_VERSION.
HAL_GetREVID()
uint32_t HAL_GetREVID (void)
Returns the device revision identifier.
Return values
Device revision identifier
Definition at line 450 of file stm32f4xx_hal.c.
 {
   return((DBGMCU->IDCODE) >> 16U);
 }
References DBGMCU.
HAL_GetTick()
__weak uint32_t HAL_GetTick (void)
Provides a tick value in millisecond.
Note
This function is declared as __weak to be overwritten in case of other implementations in user file.
Return values
tick value
Definition at line 323 of file stm32f4xx_hal.c.
 {
   return uwTick;
 }
References uwTick.
Referenced by HAL_Delay().
HAL_GetTickFreq()
HAL_TickFreqTypeDef HAL_GetTickFreq (void)
Return tick frequency.
Return values
tick period in Hz
Definition at line 373 of file stm32f4xx_hal.c.
 {
   return uwTickFreq;
 }
References uwTickFreq.
HAL_GetTickPrio()
uint32_t HAL_GetTickPrio (void)
This function returns a tick priority.
Return values
tick priority
Definition at line 332 of file stm32f4xx_hal.c.
 {
   return uwTickPrio;
 }
References uwTickPrio.
HAL_GetUIDw0()
uint32_t HAL_GetUIDw0 (void)
Returns first word of the unique device identifier (UID based on 96 bits)
Return values
Device identifier
Definition at line 544 of file stm32f4xx_hal.c.
 {
   return (READ_REG(*((uint32_t *)UID_BASE)));
 }
References READ_REG, and UID_BASE.
HAL_GetUIDw1()
uint32_t HAL_GetUIDw1 (void)
Returns second word of the unique device identifier (UID based on 96 bits)
Return values
Device identifier
Definition at line 553 of file stm32f4xx_hal.c.
 {
   return (READ_REG(*((uint32_t *)(UID_BASE + 4U))));
 }
References READ_REG, and UID_BASE.
HAL_GetUIDw2()
uint32_t HAL_GetUIDw2 (void)
Returns third word of the unique device identifier (UID based on 96 bits)
Return values
Device identifier
Definition at line 562 of file stm32f4xx_hal.c.
 {
   return (READ_REG(*((uint32_t *)(UID_BASE + 8U))));
 }
References READ_REG, and UID_BASE.
HAL_IncTick()
__weak void HAL_IncTick (void)
This function is called to increment a global variable "uwTick" used as application time base.
Note
In the default implementation, this variable is incremented each 1ms in SysTick ISR.
This function is declared as __weak to be overwritten in case of other implementations in user file.
Return values
None
Definition at line 312 of file stm32f4xx_hal.c.
 {
   uwTick += uwTickFreq;
 }
References uwTick, and uwTickFreq.
Referenced by SysTick_Handler().
HAL_ResumeTick()
__weak void HAL_ResumeTick (void)
Resume Tick increment.
Note
In the default implementation , SysTick timer is the source of time base. It is used to generate interrupts at regular time intervals. Once HAL_ResumeTick() is called, the SysTick interrupt will be enabled and so Tick increment is resumed.
This function is declared as __weak to be overwritten in case of other implementations in user file.
Return values
None
Definition at line 431 of file stm32f4xx_hal.c.
 {
   /* Enable SysTick Interrupt */
   SysTick->CTRL  |= SysTick_CTRL_TICKINT_Msk;
 }
References SysTick, and SysTick_CTRL_TICKINT_Msk.
HAL_SetTickFreq()
HAL_StatusTypeDef HAL_SetTickFreq (HAL_TickFreqTypeDef Freq)
Set new tick Freq.
Return values
Status
Definition at line 341 of file stm32f4xx_hal.c.
 {
   HAL_StatusTypeDef status  = HAL_OK;
   HAL_TickFreqTypeDef prevTickFreq;
   assert_param(IS_TICKFREQ(Freq));
   if (uwTickFreq != Freq)
   {
     /* Back up uwTickFreq frequency */
     prevTickFreq = uwTickFreq;
     /* Update uwTickFreq global variable used by HAL_InitTick() */
     uwTickFreq = Freq;
     /* Apply the new tick Freq  */
     status = HAL_InitTick(uwTickPrio);
     if (status != HAL_OK)
     {
       /* Restore previous tick frequency */
       uwTickFreq = prevTickFreq;
     }
   }
   return status;
 }
References assert_param, HAL_InitTick(), HAL_OK, IS_TICKFREQ, uwTickFreq, and uwTickPrio.
HAL_SuspendTick()
__weak void HAL_SuspendTick (void)
Suspend Tick increment.
Note
In the default implementation , SysTick timer is the source of time base. It is used to generate interrupts at regular time intervals. Once HAL_SuspendTick() is called, the SysTick interrupt will be disabled and so Tick increment is suspended.
This function is declared as __weak to be overwritten in case of other implementations in user file.
Return values
None
Definition at line 415 of file stm32f4xx_hal.c.
 {
   /* Disable SysTick Interrupt */
   SysTick->CTRL &= ~SysTick_CTRL_TICKINT_Msk;
 }
References SysTick, and SysTick_CTRL_TICKINT_Msk.