SoC Advanced: Initialization and de-initialization Functions
Initialization and de-initialization Functions
STM32F4xx_HAL_Driver » HAL » HAL Exported Functions
Initialization and de-initialization functions.
Functions
HAL_StatusTypeDef HAL_Init (void)
This function is used to initialize the HAL Library; it must be the first instruction to be executed in the main program (before to call any other HAL function), it performs the following: Configure the Flash prefetch, instruction and Data caches. Configures the SysTick to generate an interrupt each 1 millisecond, which is clocked by the HSI (at this stage, the clock is not yet configured and thus the system is running from the internal HSI at 16 MHz). Set NVIC Group Priority to 4. Calls the HAL_MspInit() callback function defined in user file "stm32f4xx_hal_msp.c" to do the global low level hardware initialization.
HAL_StatusTypeDef HAL_DeInit (void)
This function de-Initializes common part of the HAL and stops the systick. This function is optional.
void HAL_MspInit (void)
Initialize the MSP.
void HAL_MspDeInit (void)
DeInitializes the MSP.
HAL_StatusTypeDef HAL_InitTick (uint32_t TickPriority)
This function configures the source of the time base. The time source is configured to have 1ms time base with a dedicated Tick interrupt priority.
Detailed Description
Initialization and de-initialization functions.
 ===============================================================================
              ##### Initialization and Configuration functions #####
 ===============================================================================
    [..]  This section provides functions allowing to:
      (+) Initializes the Flash interface the NVIC allocation and initial clock
          configuration. It initializes the systick also when timeout is needed
          and the backup domain when enabled.
      (+) De-Initializes common part of the HAL.
      (+) Configure the time base source to have 1ms time base with a dedicated
          Tick interrupt priority.
        (++) SysTick timer is used by default as source of time base, but user
             can eventually implement his proper time base source (a general purpose
             timer for example or other time source), keeping in mind that Time base
             duration should be kept 1ms since PPP_TIMEOUT_VALUEs are defined and
             handled in milliseconds basis.
        (++) Time base configuration function (HAL_InitTick ()) is called automatically
             at the beginning of the program after reset by HAL_Init() or at any time
             when clock is configured, by HAL_RCC_ClockConfig().
        (++) Source of time base is configured  to generate interrupts at regular
             time intervals. Care must be taken if HAL_Delay() is called from a
             peripheral ISR process, the Tick interrupt line must have higher priority
            (numerically lower) than the peripheral interrupt. Otherwise the caller
            ISR process will be blocked.
       (++) functions affecting time base configurations are declared as __weak
             to make  override possible  in case of other  implementations in user file.
Function Documentation
HAL_DeInit()
HAL_StatusTypeDef HAL_DeInit (void)
This function de-Initializes common part of the HAL and stops the systick. This function is optional.
Return values
HAL status
Definition at line 190 of file stm32f4xx_hal.c.
 {
   /* Reset of all peripherals */
   __HAL_RCC_APB1_FORCE_RESET();
   __HAL_RCC_APB1_RELEASE_RESET();
   __HAL_RCC_APB2_FORCE_RESET();
   __HAL_RCC_APB2_RELEASE_RESET();
   __HAL_RCC_AHB1_FORCE_RESET();
   __HAL_RCC_AHB1_RELEASE_RESET();
   __HAL_RCC_AHB2_FORCE_RESET();
   __HAL_RCC_AHB2_RELEASE_RESET();
   __HAL_RCC_AHB3_FORCE_RESET();
   __HAL_RCC_AHB3_RELEASE_RESET();
   /* De-Init the low level hardware */
   HAL_MspDeInit();
   /* Return function status */
   return HAL_OK;
 }
References __HAL_RCC_AHB1_FORCE_RESET, __HAL_RCC_AHB1_RELEASE_RESET, __HAL_RCC_APB1_FORCE_RESET, __HAL_RCC_APB1_RELEASE_RESET, __HAL_RCC_APB2_FORCE_RESET, __HAL_RCC_APB2_RELEASE_RESET, HAL_MspDeInit(), and HAL_OK.
HAL_Init()
HAL_StatusTypeDef HAL_Init (void)
This function is used to initialize the HAL Library; it must be the first instruction to be executed in the main program (before to call any other HAL function), it performs the following: Configure the Flash prefetch, instruction and Data caches. Configures the SysTick to generate an interrupt each 1 millisecond, which is clocked by the HSI (at this stage, the clock is not yet configured and thus the system is running from the internal HSI at 16 MHz). Set NVIC Group Priority to 4. Calls the HAL_MspInit() callback function defined in user file "stm32f4xx_hal_msp.c" to do the global low level hardware initialization.
Note
SysTick is used as time base for the HAL_Delay() function, the application need to ensure that the SysTick time base is always set to 1 millisecond to have correct HAL operation.
Return values
HAL status
Definition at line 157 of file stm32f4xx_hal.c.
 {
   /* Configure Flash prefetch, Instruction cache, Data cache */
 #if (INSTRUCTION_CACHE_ENABLE != 0U)
   __HAL_FLASH_INSTRUCTION_CACHE_ENABLE();
 #endif /* INSTRUCTION_CACHE_ENABLE */
 #if (DATA_CACHE_ENABLE != 0U)
   __HAL_FLASH_DATA_CACHE_ENABLE();
 #endif /* DATA_CACHE_ENABLE */
 #if (PREFETCH_ENABLE != 0U)
   __HAL_FLASH_PREFETCH_BUFFER_ENABLE();
 #endif /* PREFETCH_ENABLE */
   /* Set Interrupt Group Priority */
   HAL_NVIC_SetPriorityGrouping(NVIC_PRIORITYGROUP_4);
   /* Use systick as time base source and configure 1ms tick (default clock after Reset is HSI) */
   HAL_InitTick(TICK_INT_PRIORITY);
   /* Init the low level hardware */
   HAL_MspInit();
   /* Return function status */
   return HAL_OK;
 }
References __HAL_FLASH_DATA_CACHE_ENABLE, __HAL_FLASH_INSTRUCTION_CACHE_ENABLE, __HAL_FLASH_PREFETCH_BUFFER_ENABLE, HAL_InitTick(), HAL_MspInit(), HAL_NVIC_SetPriorityGrouping(), HAL_OK, NVIC_PRIORITYGROUP_4, and TICK_INT_PRIORITY.
Referenced by main().
HAL_InitTick()
__weak HAL_StatusTypeDef HAL_InitTick (uint32_t TickPriority)
This function configures the source of the time base. The time source is configured to have 1ms time base with a dedicated Tick interrupt priority.
Note
This function is called automatically at the beginning of program after reset by HAL_Init() or at any time when clock is reconfigured by HAL_RCC_ClockConfig().
In the default implementation, SysTick timer is the source of time base. It is used to generate interrupts at regular time intervals. Care must be taken if HAL_Delay() is called from a peripheral ISR process, The SysTick interrupt must have higher priority (numerically lower) than the peripheral interrupt. Otherwise the caller ISR process will be blocked. The function is declared as __weak to be overwritten in case of other implementation in user file.
Parameters
TickPriority Tick interrupt priority.
Return values
HAL status
Definition at line 253 of file stm32f4xx_hal.c.
 {
   /* Configure the SysTick to have interrupt in 1ms time basis*/
   if (HAL_SYSTICK_Config(SystemCoreClock / (1000U / uwTickFreq)) > 0U)
   {
     return HAL_ERROR;
   }
   /* Configure the SysTick IRQ priority */
   if (TickPriority < (1UL << __NVIC_PRIO_BITS))
   {
     HAL_NVIC_SetPriority(SysTick_IRQn, TickPriority, 0U);
     uwTickPrio = TickPriority;
   }
   else
   {
     return HAL_ERROR;
   }
   /* Return function status */
   return HAL_OK;
 }
References __NVIC_PRIO_BITS, HAL_ERROR, HAL_NVIC_SetPriority(), HAL_OK, HAL_SYSTICK_Config(), SystemCoreClock, SysTick_IRQn, uwTickFreq, and uwTickPrio.
Referenced by HAL_Init(), and HAL_SetTickFreq().
HAL_MspDeInit()
__weak void HAL_MspDeInit (void)
DeInitializes the MSP.
Return values
None
Definition at line 230 of file stm32f4xx_hal.c.
 {
   /* NOTE : This function should not be modified, when the callback is needed,
             the HAL_MspDeInit could be implemented in the user file
    */
 }
Referenced by HAL_DeInit().
HAL_MspInit()
void HAL_MspInit (void)
Initialize the MSP.
Return values
None
Definition at line 219 of file stm32f4xx_hal.c.
 {
   /* NOTE : This function should not be modified, when the callback is needed,
             the HAL_MspInit could be implemented in the user file
    */
 }