SoC Advanced: Core/Inc/main.h File Reference
main.h File Reference
: Header for main.c file. This file contains the common defines of the application.
#include "stm32f4xx_hal.h"
Macros
#define USART_TX_Pin GPIO_PIN_2
#define USART_TX_GPIO_Port GPIOA
#define USART_RX_Pin GPIO_PIN_3
#define USART_RX_GPIO_Port GPIOA
#define TMS_Pin GPIO_PIN_13
#define TMS_GPIO_Port GPIOA
#define TCK_Pin GPIO_PIN_14
#define TCK_GPIO_Port GPIOA
#define SWO_Pin GPIO_PIN_3
#define SWO_GPIO_Port GPIOB
Functions
void Error_Handler (void)
This function is executed in case of error occurrence.
Detailed Description
: Header for main.c file. This file contains the common defines of the application.
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file main.h.
Macro Definition Documentation
SWO_GPIO_Port
#define SWO_GPIO_Port GPIOB
Definition at line 69 of file main.h.
SWO_Pin
#define SWO_Pin GPIO_PIN_3
Definition at line 68 of file main.h.
TCK_GPIO_Port
#define TCK_GPIO_Port GPIOA
Definition at line 67 of file main.h.
TCK_Pin
#define TCK_Pin GPIO_PIN_14
Definition at line 66 of file main.h.
TMS_GPIO_Port
#define TMS_GPIO_Port GPIOA
Definition at line 65 of file main.h.
TMS_Pin
#define TMS_Pin GPIO_PIN_13
Definition at line 64 of file main.h.
USART_RX_GPIO_Port
#define USART_RX_GPIO_Port GPIOA
Definition at line 63 of file main.h.
USART_RX_Pin
#define USART_RX_Pin GPIO_PIN_3
Definition at line 62 of file main.h.
USART_TX_GPIO_Port
#define USART_TX_GPIO_Port GPIOA
Definition at line 61 of file main.h.
USART_TX_Pin
#define USART_TX_Pin GPIO_PIN_2
Definition at line 60 of file main.h.
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 1218 of file main.c.
{
     /* USER CODE BEGIN Error_Handler_Debug */
     /* User can add his own implementation to report the HAL error return state */
     __disable_irq();
     while (1) {
     }
     /* USER CODE END Error_Handler_Debug */
 }
References __disable_irq().
Referenced by MX_TIM1_Init(), MX_TIM3_Init(), MX_TIM4_Init(), MX_TIM8_Init(), MX_USART2_UART_Init(), and SystemClock_Config().