SoC Advanced: Core/Src/main.c File Reference
main.c File Reference
: Main program body
#include "main.h"
#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>
#include <time.h>
Macros
#define TRIG_PIN GPIO_PIN_8
#define TRIG_PORT GPIOC
#define WINDOW_SIZE 3
#define THRESHOLD 10
#define STRIKE_LIMIT 3
Functions
void SystemClock_Config (void)
System Clock Configuration.
static void MX_GPIO_Init (void)
GPIO Initialization Function.
static void MX_USART2_UART_Init (void)
USART2 Initialization Function.
static void MX_TIM1_Init (void)
TIM1 Initialization Function.
static void MX_TIM8_Init (void)
TIM8 Initialization Function.
static void MX_TIM3_Init (void)
TIM3 Initialization Function.
static void MX_TIM4_Init (void)
TIM4 Initialization Function.
void turn_ignition_on ()
Emulates turning on the car ignition.
void turn_vehicle_on ()
Emulates turning on the car.
bool check_alcohol_level ()
Checks alcohol level to determine if car is allowed to be started (low alcohol level) or if car is not allowed to start (high alcohol level.)
void start_measurement ()
Triggers the sensors to start measuring the distances.
void uS_delay (uint16_t delay)
Delay function in microseconds.
void HAL_TIM_IC_CaptureCallback (TIM_HandleTypeDef *htim)
Callback function to capture inputs from the distance sensors on change.
void verify_sensor_measurements ()
Verifying the new captured value of all sensors using a "Running Median" algorithm with a given THRESHOLD value, to detect outliers and possible sensor malfunction during runtime.
float calculate_median (float *data_points)
Calculates the median of an unsorted array using the Quick Select algorithm for performance boost.
void median_util (float *arr, int l, int r, int k, int *a, int *b)
Utility function to find median.
int random_partition (float *arr, int l, int r)
Picks a random pivot element between l and r and partitions arr[l..r] around the randomly picked element.
int partition (float *arr, int l, int r)
Calculates the correct position of pivot element.
void swap (float *a, float *b)
Swapping elements.
void check_sensor_measurements ()
Checks sensors states and and assigns final distance values through cross checking.
void check_distance_status ()
Checks if distances abide by specifications to detect if objects are to close.
void HAL_GPIO_EXTI_Callback (uint16_t GPIO_Pin)
Callback function to capture changes on Push Button line and IR sensor line for Eye blinking tracking.
void driver_asleep ()
After sleep detection, emulate vehicle going into Safe-State and notify through alarm that sleep was detected.
void turn_vehicle_off ()
Emulates vehicle shutdown.
void turn_ignition_off ()
Emulates ignition shutdown.
int main (void)
The application entry point.
void Error_Handler (void)
This function is executed in case of error occurrence.
Variables
TIM_HandleTypeDef htim1
TIM_HandleTypeDef htim3
TIM_HandleTypeDef htim4
TIM_HandleTypeDef htim8
UART_HandleTypeDef huart2
bool is_car_on = false
bool is_ignition_on = false
bool is_sleep_detected = false
uint32_t oneSec = 0
uint32_t twoSec = 0
uint8_t measurements_count = 0
float final_front_distance = 0
float final_back_distance = 0
uint32_t start_of_pulse_front_sensor1 = 0
uint32_t end_of_pulse_front_sensor1 = 0
uint32_t difference_front_sensor1 = 0
bool is_start_captured_front_sensor1 = false
float distance_front_sensor1 = 0
float window_front_sensor1 [WINDOW_SIZE]
bool is_front_sensor1_operative = true
uint8_t front_sensor1_strikes = 0
uint32_t start_of_pulse_front_sensor2 = 0
uint32_t end_of_pulse_front_sensor2 = 0
uint32_t difference_front_sensor2 = 0
bool is_start_captured_front_sensor2 = false
float distance_front_sensor2 = 0
float window_front_sensor2 [WINDOW_SIZE]
bool is_front_sensor2_operative = true
uint8_t front_sensor2_strikes = 0
uint32_t start_of_pulse_back_sensor1 = 0
uint32_t end_of_pulse_back_sensor1 = 0
uint32_t difference_back_sensor1 = 0
bool is_start_captured_back_sensor1 = false
float distance_back_sensor1 = 0
float window_back_sensor1 [WINDOW_SIZE]
bool is_back_sensor1_operative = true
uint8_t back_sensor1_strikes = 0
uint32_t start_of_pulse_back_sensor2 = 0
uint32_t end_of_pulse_back_sensor2 = 0
uint32_t difference_back_sensor2 = 0
bool is_start_captured_back_sensor2 = false
float distance_back_sensor2 = 0
float window_back_sensor2 [WINDOW_SIZE]
bool is_back_sensor2_operative = true
uint8_t back_sensor2_strikes = 0
Detailed Description
: Main program body
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file main.c.
Macro Definition Documentation
STRIKE_LIMIT
#define STRIKE_LIMIT 3
Definition at line 48 of file main.c.
THRESHOLD
#define THRESHOLD 10
Definition at line 47 of file main.c.
TRIG_PIN
#define TRIG_PIN GPIO_PIN_8
Definition at line 44 of file main.c.
TRIG_PORT
#define TRIG_PORT GPIOC
Definition at line 45 of file main.c.
WINDOW_SIZE
#define WINDOW_SIZE 3
Definition at line 46 of file main.c.
Function Documentation
calculate_median()
float calculate_median (float * data_points)
Calculates the median of an unsorted array using the Quick Select algorithm for performance boost.
Parameters
[in] data_points An array of a given WINDOW_SIZE containing the previous and new measured values.
Return values
ans The calculated median.
Definition at line 518 of file main.c.
{
     int ans = 0;
     int a = -1;
     int b = -1;
     int n = WINDOW_SIZE;
     // If n is odd
     if (n % 2 == 1) {
         median_util(data_points, 0, n - 1, n / 2, &a, &b);
         ans = b;
     }
     // If n is even
     else {
         median_util(data_points, 0, n - 1, n / 2, &a, &b);
         ans = (a + b) / 2;
     }
     return ans;
 }
References median_util(), and WINDOW_SIZE.
Referenced by verify_sensor_measurements().
check_alcohol_level()
bool check_alcohol_level ()
Checks alcohol level to determine if car is allowed to be started (low alcohol level) or if car is not allowed to start (high alcohol level.)
Parameters
None
Return values
false Alcohol level low --> start car
true Alcohol level high --> turn car off
Definition at line 185 of file main.c.
{
     char txt[] = "Testing alcohol level...\n\r";
     HAL_UART_Transmit(&huart2, (const uint8_t*) txt, strlen(txt), 100);
     HAL_Delay(5000);
     if (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_0) == GPIO_PIN_RESET) {
         char txt[] = "Alcohol level high! ";
         HAL_UART_Transmit(&huart2, (const uint8_t*) txt, strlen(txt), 100);
         return true;
     }
     else {
         char txt[] = "Alcohol level low. ";
         HAL_UART_Transmit(&huart2, (const uint8_t*) txt, strlen(txt), 100);
         return false;
     }
 }
References GPIO_PIN_0, GPIO_PIN_RESET, GPIOC, HAL_Delay(), HAL_GPIO_ReadPin(), HAL_UART_Transmit(), and huart2.
Referenced by main().
check_distance_status()
void check_distance_status ()
Checks if distances abide by specifications to detect if objects are to close.
Parameters
None
Return values
None.
Definition at line 709 of file main.c.
{
     char buffer_front[26]; // buffer to store the string
     char buffer_back[25]; // buffer to store the string
     sprintf(buffer_front, "Front distance: %.2f cm\n\r", final_front_distance);
     sprintf(buffer_back, "Back distance: %.2f cm\n\r", final_back_distance);
     if (final_front_distance < 5.0 || final_back_distance < 5) {
         HAL_GPIO_WritePin(GPIOC, GPIO_PIN_9, GPIO_PIN_RESET);
         HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, GPIO_PIN_SET);
         if (oneSec > 1000) {
             HAL_UART_Transmit(&huart2, (const uint8_t*) buffer_front,
                     strlen(buffer_front), 100);
             HAL_UART_Transmit(&huart2, (const uint8_t*) buffer_back,
                     strlen(buffer_back), 100);
             oneSec = 0;
         }
         oneSec += 20;
         twoSec += 20;
         HAL_Delay(20);
     } else {
         HAL_GPIO_WritePin(GPIOC, GPIO_PIN_9, GPIO_PIN_SET);
         HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, GPIO_PIN_RESET);
         if (oneSec > 1000) {
             HAL_UART_Transmit(&huart2, (const uint8_t*) buffer_front,
                     strlen(buffer_front), 100);
             HAL_UART_Transmit(&huart2, (const uint8_t*) buffer_back,
                     strlen(buffer_back), 100);
             oneSec = 0;
         }
         oneSec += 40;
         twoSec += 40;
         HAL_Delay(40);
     }
     if (is_sleep_detected == true && twoSec > 2000) {
         driver_asleep();
     }
 }
References driver_asleep(), final_back_distance, final_front_distance, GPIO_PIN_12, GPIO_PIN_9, GPIO_PIN_RESET, GPIO_PIN_SET, GPIOA, GPIOC, HAL_Delay(), HAL_GPIO_WritePin(), HAL_UART_Transmit(), huart2, is_sleep_detected, oneSec, and twoSec.
Referenced by check_sensor_measurements().
check_sensor_measurements()
void check_sensor_measurements ()
Checks sensors states and and assigns final distance values through cross checking.
Parameters
None
Return values
None.
Definition at line 648 of file main.c.
{
     bool isContinue = false;
     // Both sensors operational
     if (is_front_sensor1_operative == true && is_front_sensor2_operative == true) {
         final_front_distance = (distance_front_sensor1 + distance_front_sensor2)
                 / 2.0;
         isContinue = true;
     }
     // One sensor faulty
     else if (is_front_sensor1_operative == false
             && is_front_sensor2_operative == true) {
         final_front_distance = distance_front_sensor2;
         isContinue = true;
     } else if (is_front_sensor1_operative == true
             && is_front_sensor2_operative == false) {
         final_front_distance = distance_front_sensor1;
         isContinue = true;
     }
     // Both sensors faulty
     else {
         char txt[] =
                 "Both front sensors failed!\n\rEntering Safe-State-Mode!\n\r";
         HAL_UART_Transmit(&huart2, (const uint8_t*) txt, strlen(txt), 100);
         turn_vehicle_off();
     }
     // Both sensors operational
     if (is_back_sensor1_operative == true && is_back_sensor2_operative == true) {
         final_back_distance = (distance_back_sensor1 + distance_back_sensor2)
                 / 2.0;
         isContinue = true;
     }
     // One sensor faulty
     else if (is_back_sensor1_operative == false
             && is_back_sensor2_operative == true) {
         final_back_distance = distance_back_sensor2;
         isContinue = true;
     } else if (is_back_sensor1_operative == true
             && is_back_sensor2_operative == false) {
         final_back_distance = distance_back_sensor1;
         isContinue = true;
     }
     // Both sensors faulty
     else {
         char txt[] = "Both back sensors failed!\n\rGoing into Safe-State!\n\r";
         HAL_UART_Transmit(&huart2, (const uint8_t*) txt, strlen(txt), 100);
         turn_vehicle_off();
     }
     if (isContinue == true) {
         check_distance_status();
     }
 }
References check_distance_status(), distance_back_sensor1, distance_back_sensor2, distance_front_sensor1, distance_front_sensor2, final_back_distance, final_front_distance, HAL_UART_Transmit(), huart2, is_back_sensor1_operative, is_back_sensor2_operative, is_front_sensor1_operative, is_front_sensor2_operative, and turn_vehicle_off().
Referenced by main().
driver_asleep()
void driver_asleep ()
After sleep detection, emulate vehicle going into Safe-State and notify through alarm that sleep was detected.
Parameters
None
Return values
None.
Definition at line 788 of file main.c.
                      {
     char txt[] = "Driver  asleep!\n\rEntering Safe-State-Mode!\n\r";
     HAL_UART_Transmit(&huart2, (const uint8_t*) txt, strlen(txt), 100);
     HAL_GPIO_WritePin(GPIOC, GPIO_PIN_9, GPIO_PIN_RESET);
     HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, GPIO_PIN_SET);
     HAL_Delay(2000);
     is_sleep_detected = false;
     turn_vehicle_off();
 }
References GPIO_PIN_12, GPIO_PIN_9, GPIO_PIN_RESET, GPIO_PIN_SET, GPIOA, GPIOC, HAL_Delay(), HAL_GPIO_WritePin(), HAL_UART_Transmit(), huart2, is_sleep_detected, and turn_vehicle_off().
Referenced by check_distance_status().
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 1218 of file main.c.
{
     /* USER CODE BEGIN Error_Handler_Debug */
     /* User can add his own implementation to report the HAL error return state */
     __disable_irq();
     while (1) {
     }
     /* USER CODE END Error_Handler_Debug */
 }
References __disable_irq().
Referenced by MX_TIM1_Init(), MX_TIM3_Init(), MX_TIM4_Init(), MX_TIM8_Init(), MX_USART2_UART_Init(), and SystemClock_Config().
main()
int main (void)
The application entry point.
Return values
int
Definition at line 831 of file main.c.
                {
     /* USER CODE BEGIN 1 */
     /* USER CODE END 1 */
     /* MCU Configuration--------------------------------------------------------*/
     /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
     HAL_Init();
     /* USER CODE BEGIN Init */
     /* USER CODE END Init */
     /* Configure the system clock */
     SystemClock_Config();
     /* USER CODE BEGIN SysInit */
     /* USER CODE END SysInit */
     /* Initialize all configured peripherals */
     MX_GPIO_Init();
     MX_USART2_UART_Init();
     MX_TIM1_Init();
     MX_TIM8_Init();
     MX_TIM3_Init();
     MX_TIM4_Init();
     /* USER CODE BEGIN 2 */
     HAL_TIM_IC_Start_IT(&htim1, TIM_CHANNEL_1);
     HAL_TIM_IC_Start_IT(&htim8, TIM_CHANNEL_1);
     HAL_TIM_IC_Start_IT(&htim3, TIM_CHANNEL_1);
     HAL_TIM_IC_Start_IT(&htim4, TIM_CHANNEL_1);
     /* USER CODE END 2 */
     /* Infinite loop */
     /* USER CODE BEGIN WHILE */
     while (1) {
         if (is_ignition_on == true) {
             if (is_car_on == false) {
                 if (check_alcohol_level() == true) {
                     turn_vehicle_off();
                 } else {
                     turn_vehicle_on();
                     //start_measurement();
                 }
             } else {
                 while (is_car_on == true) {
                     start_measurement();
                     verify_sensor_measurements();
                     check_sensor_measurements();
                 }
             }
         }
         /* USER CODE END WHILE */
         /* USER CODE BEGIN 3 */
     }
     /* USER CODE END 3 */
 }
References check_alcohol_level(), check_sensor_measurements(), HAL_Init(), HAL_TIM_IC_Start_IT(), htim1, htim3, htim4, htim8, is_car_on, is_ignition_on, MX_GPIO_Init(), MX_TIM1_Init(), MX_TIM3_Init(), MX_TIM4_Init(), MX_TIM8_Init(), MX_USART2_UART_Init(), start_measurement(), SystemClock_Config(), TIM_CHANNEL_1, turn_vehicle_off(), turn_vehicle_on(), and verify_sensor_measurements().
median_util()
void median_util (float * arr, int l, int r, int k, int * a, int * b)
Utility function to find median.
Parameters
[in] arr An array of a given WINDOW_SIZE containing the previous and new measured values.
[in] l Index of the left most value.
[in] r Index of the right most value.
[in] k Index of the median if list/array were to be sorted.
[in] a Helper value to get final result.
[in] b Helper value to get final result.
Return values
None
Definition at line 548 of file main.c.
{
     // if l < r
     if (l <= r) {
         // Find the partition index
         int partitionIndex = random_partition(arr, l, r);
         // If partition index = k, then
         // we found the median of odd
         // number element in arr[]
         if (partitionIndex == k) {
             *b = arr[partitionIndex];
             if (*a != -1)
                 return;
         }
         // If index = k - 1, then we get
         // a & b as middle element of
         // arr[]
         else if (partitionIndex == k - 1) {
             *a = arr[partitionIndex];
             if (*b != -1)
                 return;
         }
         // If partitionIndex >= k then
         // find the index in first half
         // of the arr[]
         if (partitionIndex >= k)
             return median_util(arr, l, partitionIndex - 1, k, a, b);
         // If partitionIndex <= k then
         // find the index in second half
         // of the arr[]
         else
             return median_util(arr, partitionIndex + 1, r, k, a, b);
     }
     return;
 }
References random_partition().
Referenced by calculate_median().
MX_GPIO_Init()
static void MX_GPIO_Init (void) static
GPIO Initialization Function.
Parameters
None
Return values
None
Definition at line 1156 of file main.c.
{
     GPIO_InitTypeDef GPIO_InitStruct = { 0 };
     /* USER CODE BEGIN MX_GPIO_Init_1 */
     /* USER CODE END MX_GPIO_Init_1 */
     /* GPIO Ports Clock Enable */
     __HAL_RCC_GPIOC_CLK_ENABLE();
     __HAL_RCC_GPIOH_CLK_ENABLE();
     __HAL_RCC_GPIOA_CLK_ENABLE();
     __HAL_RCC_GPIOB_CLK_ENABLE();
     /*Configure GPIO pin Output Level */
     HAL_GPIO_WritePin(GPIOC, GPIO_PIN_8 | GPIO_PIN_9, GPIO_PIN_RESET);
     /*Configure GPIO pin Output Level */
     HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, GPIO_PIN_RESET);
     /*Configure GPIO pins : PC13 PC7 */
     GPIO_InitStruct.Pin = GPIO_PIN_13 | GPIO_PIN_7;
     GPIO_InitStruct.Mode = GPIO_MODE_IT_RISING_FALLING;
     GPIO_InitStruct.Pull = GPIO_NOPULL;
     HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
     /*Configure GPIO pin : PC0 */
     GPIO_InitStruct.Pin = GPIO_PIN_0;
     GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
     GPIO_InitStruct.Pull = GPIO_NOPULL;
     HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
     /*Configure GPIO pins : PC8 PC9 */
     GPIO_InitStruct.Pin = GPIO_PIN_8 | GPIO_PIN_9;
     GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
     GPIO_InitStruct.Pull = GPIO_NOPULL;
     GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
     HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
     /*Configure GPIO pin : PA12 */
     GPIO_InitStruct.Pin = GPIO_PIN_12;
     GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
     GPIO_InitStruct.Pull = GPIO_NOPULL;
     GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
     HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
     /* EXTI interrupt init*/
     HAL_NVIC_SetPriority(EXTI9_5_IRQn, 0, 0);
     HAL_NVIC_EnableIRQ(EXTI9_5_IRQn);
     HAL_NVIC_SetPriority(EXTI15_10_IRQn, 0, 0);
     HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);
     /* USER CODE BEGIN MX_GPIO_Init_2 */
     /* USER CODE END MX_GPIO_Init_2 */
 }
References __HAL_RCC_GPIOA_CLK_ENABLE, __HAL_RCC_GPIOB_CLK_ENABLE, __HAL_RCC_GPIOC_CLK_ENABLE, __HAL_RCC_GPIOH_CLK_ENABLE, EXTI15_10_IRQn, EXTI9_5_IRQn, GPIO_MODE_INPUT, GPIO_MODE_IT_RISING_FALLING, GPIO_MODE_OUTPUT_PP, GPIO_NOPULL, GPIO_PIN_0, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_7, GPIO_PIN_8, GPIO_PIN_9, GPIO_PIN_RESET, GPIO_SPEED_FREQ_LOW, GPIOA, GPIOC, HAL_GPIO_Init(), HAL_GPIO_WritePin(), HAL_NVIC_EnableIRQ(), HAL_NVIC_SetPriority(), GPIO_InitTypeDef::Mode, GPIO_InitTypeDef::Pin, GPIO_InitTypeDef::Pull, and GPIO_InitTypeDef::Speed.
Referenced by main().
MX_TIM1_Init()
static void MX_TIM1_Init (void) static
TIM1 Initialization Function.
Parameters
None
Return values
None
Definition at line 943 of file main.c.
{
     /* USER CODE BEGIN TIM1_Init 0 */
     /* USER CODE END TIM1_Init 0 */
     TIM_MasterConfigTypeDef sMasterConfig = { 0 };
     TIM_IC_InitTypeDef sConfigIC = { 0 };
     /* USER CODE BEGIN TIM1_Init 1 */
     /* USER CODE END TIM1_Init 1 */
     htim1.Instance = TIM1;
     htim1.Init.Prescaler = 84 - 1;
     htim1.Init.CounterMode = TIM_COUNTERMODE_UP;
     htim1.Init.Period = 65535;
     htim1.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
     htim1.Init.RepetitionCounter = 0;
     htim1.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
     if (HAL_TIM_IC_Init(&htim1) != HAL_OK) {
         Error_Handler();
     }
     sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
     sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
     if (HAL_TIMEx_MasterConfigSynchronization(&htim1, &sMasterConfig)
             != HAL_OK) {
         Error_Handler();
     }
     sConfigIC.ICPolarity = TIM_INPUTCHANNELPOLARITY_RISING;
     sConfigIC.ICSelection = TIM_ICSELECTION_DIRECTTI;
     sConfigIC.ICPrescaler = TIM_ICPSC_DIV1;
     sConfigIC.ICFilter = 0;
     if (HAL_TIM_IC_ConfigChannel(&htim1, &sConfigIC, TIM_CHANNEL_1) != HAL_OK) {
         Error_Handler();
     }
     /* USER CODE BEGIN TIM1_Init 2 */
     /* USER CODE END TIM1_Init 2 */
 }
References TIM_Base_InitTypeDef::AutoReloadPreload, TIM_Base_InitTypeDef::ClockDivision, TIM_Base_InitTypeDef::CounterMode, Error_Handler(), HAL_OK, HAL_TIM_IC_ConfigChannel(), HAL_TIM_IC_Init(), HAL_TIMEx_MasterConfigSynchronization(), htim1, TIM_IC_InitTypeDef::ICFilter, TIM_IC_InitTypeDef::ICPolarity, TIM_IC_InitTypeDef::ICPrescaler, TIM_IC_InitTypeDef::ICSelection, TIM_HandleTypeDef::Init, TIM_HandleTypeDef::Instance, TIM_MasterConfigTypeDef::MasterOutputTrigger, TIM_MasterConfigTypeDef::MasterSlaveMode, TIM_Base_InitTypeDef::Period, TIM_Base_InitTypeDef::Prescaler, TIM_Base_InitTypeDef::RepetitionCounter, TIM1, TIM_AUTORELOAD_PRELOAD_DISABLE, TIM_CHANNEL_1, TIM_CLOCKDIVISION_DIV1, TIM_COUNTERMODE_UP, TIM_ICPSC_DIV1, TIM_ICSELECTION_DIRECTTI, TIM_INPUTCHANNELPOLARITY_RISING, TIM_MASTERSLAVEMODE_DISABLE, and TIM_TRGO_RESET.
Referenced by main().
MX_TIM3_Init()
static void MX_TIM3_Init (void) static
TIM3 Initialization Function.
Parameters
None
Return values
None
Definition at line 989 of file main.c.
{
     /* USER CODE BEGIN TIM3_Init 0 */
     /* USER CODE END TIM3_Init 0 */
     TIM_MasterConfigTypeDef sMasterConfig = { 0 };
     TIM_IC_InitTypeDef sConfigIC = { 0 };
     /* USER CODE BEGIN TIM3_Init 1 */
     /* USER CODE END TIM3_Init 1 */
     htim3.Instance = TIM3;
     htim3.Init.Prescaler = 84 - 1;
     htim3.Init.CounterMode = TIM_COUNTERMODE_UP;
     htim3.Init.Period = 65535;
     htim3.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
     htim3.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
     if (HAL_TIM_IC_Init(&htim3) != HAL_OK) {
         Error_Handler();
     }
     sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
     sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
     if (HAL_TIMEx_MasterConfigSynchronization(&htim3, &sMasterConfig)
             != HAL_OK) {
         Error_Handler();
     }
     sConfigIC.ICPolarity = TIM_INPUTCHANNELPOLARITY_RISING;
     sConfigIC.ICSelection = TIM_ICSELECTION_DIRECTTI;
     sConfigIC.ICPrescaler = TIM_ICPSC_DIV1;
     sConfigIC.ICFilter = 0;
     if (HAL_TIM_IC_ConfigChannel(&htim3, &sConfigIC, TIM_CHANNEL_1) != HAL_OK) {
         Error_Handler();
     }
     /* USER CODE BEGIN TIM3_Init 2 */
     /* USER CODE END TIM3_Init 2 */
 }
References TIM_Base_InitTypeDef::AutoReloadPreload, TIM_Base_InitTypeDef::ClockDivision, TIM_Base_InitTypeDef::CounterMode, Error_Handler(), HAL_OK, HAL_TIM_IC_ConfigChannel(), HAL_TIM_IC_Init(), HAL_TIMEx_MasterConfigSynchronization(), htim3, TIM_IC_InitTypeDef::ICFilter, TIM_IC_InitTypeDef::ICPolarity, TIM_IC_InitTypeDef::ICPrescaler, TIM_IC_InitTypeDef::ICSelection, TIM_HandleTypeDef::Init, TIM_HandleTypeDef::Instance, TIM_MasterConfigTypeDef::MasterOutputTrigger, TIM_MasterConfigTypeDef::MasterSlaveMode, TIM_Base_InitTypeDef::Period, TIM_Base_InitTypeDef::Prescaler, TIM3, TIM_AUTORELOAD_PRELOAD_DISABLE, TIM_CHANNEL_1, TIM_CLOCKDIVISION_DIV1, TIM_COUNTERMODE_UP, TIM_ICPSC_DIV1, TIM_ICSELECTION_DIRECTTI, TIM_INPUTCHANNELPOLARITY_RISING, TIM_MASTERSLAVEMODE_DISABLE, and TIM_TRGO_RESET.
Referenced by main().
MX_TIM4_Init()
static void MX_TIM4_Init (void) static
TIM4 Initialization Function.
Parameters
None
Return values
None
Definition at line 1034 of file main.c.
{
     /* USER CODE BEGIN TIM4_Init 0 */
     /* USER CODE END TIM4_Init 0 */
     TIM_MasterConfigTypeDef sMasterConfig = { 0 };
     TIM_IC_InitTypeDef sConfigIC = { 0 };
     /* USER CODE BEGIN TIM4_Init 1 */
     /* USER CODE END TIM4_Init 1 */
     htim4.Instance = TIM4;
     htim4.Init.Prescaler = 84 - 1;
     htim4.Init.CounterMode = TIM_COUNTERMODE_UP;
     htim4.Init.Period = 65535;
     htim4.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
     htim4.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
     if (HAL_TIM_IC_Init(&htim4) != HAL_OK) {
         Error_Handler();
     }
     sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
     sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
     if (HAL_TIMEx_MasterConfigSynchronization(&htim4, &sMasterConfig)
             != HAL_OK) {
         Error_Handler();
     }
     sConfigIC.ICPolarity = TIM_INPUTCHANNELPOLARITY_RISING;
     sConfigIC.ICSelection = TIM_ICSELECTION_DIRECTTI;
     sConfigIC.ICPrescaler = TIM_ICPSC_DIV1;
     sConfigIC.ICFilter = 0;
     if (HAL_TIM_IC_ConfigChannel(&htim4, &sConfigIC, TIM_CHANNEL_1) != HAL_OK) {
         Error_Handler();
     }
     /* USER CODE BEGIN TIM4_Init 2 */
     /* USER CODE END TIM4_Init 2 */
 }
References TIM_Base_InitTypeDef::AutoReloadPreload, TIM_Base_InitTypeDef::ClockDivision, TIM_Base_InitTypeDef::CounterMode, Error_Handler(), HAL_OK, HAL_TIM_IC_ConfigChannel(), HAL_TIM_IC_Init(), HAL_TIMEx_MasterConfigSynchronization(), htim4, TIM_IC_InitTypeDef::ICFilter, TIM_IC_InitTypeDef::ICPolarity, TIM_IC_InitTypeDef::ICPrescaler, TIM_IC_InitTypeDef::ICSelection, TIM_HandleTypeDef::Init, TIM_HandleTypeDef::Instance, TIM_MasterConfigTypeDef::MasterOutputTrigger, TIM_MasterConfigTypeDef::MasterSlaveMode, TIM_Base_InitTypeDef::Period, TIM_Base_InitTypeDef::Prescaler, TIM4, TIM_AUTORELOAD_PRELOAD_DISABLE, TIM_CHANNEL_1, TIM_CLOCKDIVISION_DIV1, TIM_COUNTERMODE_UP, TIM_ICPSC_DIV1, TIM_ICSELECTION_DIRECTTI, TIM_INPUTCHANNELPOLARITY_RISING, TIM_MASTERSLAVEMODE_DISABLE, and TIM_TRGO_RESET.
Referenced by main().
MX_TIM8_Init()
static void MX_TIM8_Init (void) static
TIM8 Initialization Function.
Parameters
None
Return values
None
Definition at line 1079 of file main.c.
{
     /* USER CODE BEGIN TIM8_Init 0 */
     /* USER CODE END TIM8_Init 0 */
     TIM_MasterConfigTypeDef sMasterConfig = { 0 };
     TIM_IC_InitTypeDef sConfigIC = { 0 };
     /* USER CODE BEGIN TIM8_Init 1 */
     /* USER CODE END TIM8_Init 1 */
     htim8.Instance = TIM8;
     htim8.Init.Prescaler = 84 - 1;
     htim8.Init.CounterMode = TIM_COUNTERMODE_UP;
     htim8.Init.Period = 65535;
     htim8.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
     htim8.Init.RepetitionCounter = 0;
     htim8.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
     if (HAL_TIM_IC_Init(&htim8) != HAL_OK) {
         Error_Handler();
     }
     sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
     sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
     if (HAL_TIMEx_MasterConfigSynchronization(&htim8, &sMasterConfig)
             != HAL_OK) {
         Error_Handler();
     }
     sConfigIC.ICPolarity = TIM_INPUTCHANNELPOLARITY_RISING;
     sConfigIC.ICSelection = TIM_ICSELECTION_DIRECTTI;
     sConfigIC.ICPrescaler = TIM_ICPSC_DIV1;
     sConfigIC.ICFilter = 0;
     if (HAL_TIM_IC_ConfigChannel(&htim8, &sConfigIC, TIM_CHANNEL_1) != HAL_OK) {
         Error_Handler();
     }
     /* USER CODE BEGIN TIM8_Init 2 */
     /* USER CODE END TIM8_Init 2 */
 }
References TIM_Base_InitTypeDef::AutoReloadPreload, TIM_Base_InitTypeDef::ClockDivision, TIM_Base_InitTypeDef::CounterMode, Error_Handler(), HAL_OK, HAL_TIM_IC_ConfigChannel(), HAL_TIM_IC_Init(), HAL_TIMEx_MasterConfigSynchronization(), htim8, TIM_IC_InitTypeDef::ICFilter, TIM_IC_InitTypeDef::ICPolarity, TIM_IC_InitTypeDef::ICPrescaler, TIM_IC_InitTypeDef::ICSelection, TIM_HandleTypeDef::Init, TIM_HandleTypeDef::Instance, TIM_MasterConfigTypeDef::MasterOutputTrigger, TIM_MasterConfigTypeDef::MasterSlaveMode, TIM_Base_InitTypeDef::Period, TIM_Base_InitTypeDef::Prescaler, TIM_Base_InitTypeDef::RepetitionCounter, TIM8, TIM_AUTORELOAD_PRELOAD_DISABLE, TIM_CHANNEL_1, TIM_CLOCKDIVISION_DIV1, TIM_COUNTERMODE_UP, TIM_ICPSC_DIV1, TIM_ICSELECTION_DIRECTTI, TIM_INPUTCHANNELPOLARITY_RISING, TIM_MASTERSLAVEMODE_DISABLE, and TIM_TRGO_RESET.
Referenced by main().
MX_USART2_UART_Init()
static void MX_USART2_UART_Init (void) static
USART2 Initialization Function.
Parameters
None
Return values
None
Definition at line 1125 of file main.c.
{
     /* USER CODE BEGIN USART2_Init 0 */
     /* USER CODE END USART2_Init 0 */
     /* USER CODE BEGIN USART2_Init 1 */
     /* USER CODE END USART2_Init 1 */
     huart2.Instance = USART2;
     huart2.Init.BaudRate = 115200;
     huart2.Init.WordLength = UART_WORDLENGTH_8B;
     huart2.Init.StopBits = UART_STOPBITS_1;
     huart2.Init.Parity = UART_PARITY_NONE;
     huart2.Init.Mode = UART_MODE_TX_RX;
     huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
     huart2.Init.OverSampling = UART_OVERSAMPLING_16;
     if (HAL_UART_Init(&huart2) != HAL_OK) {
         Error_Handler();
     }
     /* USER CODE BEGIN USART2_Init 2 */
     /* USER CODE END USART2_Init 2 */
 }
References UART_InitTypeDef::BaudRate, Error_Handler(), HAL_OK, HAL_UART_Init(), huart2, UART_InitTypeDef::HwFlowCtl, __UART_HandleTypeDef::Init, __UART_HandleTypeDef::Instance, UART_InitTypeDef::Mode, UART_InitTypeDef::OverSampling, UART_InitTypeDef::Parity, UART_InitTypeDef::StopBits, UART_HWCONTROL_NONE, UART_MODE_TX_RX, UART_OVERSAMPLING_16, UART_PARITY_NONE, UART_STOPBITS_1, UART_WORDLENGTH_8B, USART2, and UART_InitTypeDef::WordLength.
Referenced by main().
partition()
int partition (float * arr, int l, int r)
Calculates the correct position of pivot element.
Parameters
[in] arr An array of a given WINDOW_SIZE containing the previous and new measured values.
[in] l Index of the left most value.
[in] r Index of the right most value.
Return values
i Correct position of pivot element.
Definition at line 614 of file main.c.
{
     float lst = arr[r];
     int i = l;
     int j = l;
     while (j < r) {
         if (arr[j] < lst) {
             swap(&arr[i], &arr[j]);
             i++;
         }
         j++;
     }
     swap(&arr[i], &arr[r]);
     return i;
 }
References swap().
Referenced by random_partition().
random_partition()
int random_partition (float * arr, int l, int r)
Picks a random pivot element between l and r and partitions arr[l..r] around the randomly picked element.
Parameters
[in] arr An array of a given WINDOW_SIZE containing the previous and new measured values.
[in] l
[in] r
Return values
p Correct position of pivot element.
Definition at line 597 of file main.c.
{
     int n = r - l + 1;
     int pivot = rand() % n;
     swap(&arr[l + pivot], &arr[r]);
     int p = partition(arr, l, r);
     return p;
 }
References partition(), and swap().
Referenced by median_util().
start_measurement()
void start_measurement ()
Triggers the sensors to start measuring the distances.
Parameters
None
Return values
None
Definition at line 210 of file main.c.
{
     // Pull pin high for 10 us to trigger measurement
     HAL_GPIO_WritePin(TRIG_PORT, TRIG_PIN, GPIO_PIN_SET);
     uS_delay(10);
     HAL_GPIO_WritePin(TRIG_PORT, TRIG_PIN, GPIO_PIN_RESET);
     // Only trigger sensor measurement if sensor is not disabled
     if (is_front_sensor1_operative == true) {
         __HAL_TIM_ENABLE_IT(&htim1, TIM_IT_CC1);
     }
     if (is_front_sensor2_operative == true) {
         __HAL_TIM_ENABLE_IT(&htim8, TIM_IT_CC1);
     }
     if (is_back_sensor2_operative == true) {
         __HAL_TIM_ENABLE_IT(&htim3, TIM_IT_CC1);
     }
     if (is_back_sensor1_operative == true) {
         __HAL_TIM_ENABLE_IT(&htim4, TIM_IT_CC1);
     }
     measurements_count =
             measurements_count < 3 ?
                     measurements_count + 1 : measurements_count;
 }
References __HAL_TIM_ENABLE_IT, GPIO_PIN_RESET, GPIO_PIN_SET, HAL_GPIO_WritePin(), htim1, htim3, htim4, htim8, is_back_sensor1_operative, is_back_sensor2_operative, is_front_sensor1_operative, is_front_sensor2_operative, measurements_count, TIM_IT_CC1, TRIG_PIN, TRIG_PORT, and uS_delay().
Referenced by main().
swap()
void swap (float * a, float * b)
Swapping elements.
Parameters
[in] a Element to be swapped.
[in] b Element to be swapped.
Return values
None.
Definition at line 636 of file main.c.
{
     float temp = *a;
     *a = *b;
     *b = temp;
 }
Referenced by partition(), and random_partition().
SystemClock_Config()
void SystemClock_Config (void)
System Clock Configuration.
Return values
None
Configure the main internal regulator output voltage
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
Initializes the CPU, AHB and APB buses clocks
Definition at line 898 of file main.c.
{
     RCC_OscInitTypeDef RCC_OscInitStruct = { 0 };
     RCC_ClkInitTypeDef RCC_ClkInitStruct = { 0 };
     __HAL_RCC_PWR_CLK_ENABLE();
     __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE3);
     RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
     RCC_OscInitStruct.HSIState = RCC_HSI_ON;
     RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
     RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
     RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
     RCC_OscInitStruct.PLL.PLLM = 16;
     RCC_OscInitStruct.PLL.PLLN = 336;
     RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV4;
     RCC_OscInitStruct.PLL.PLLQ = 2;
     RCC_OscInitStruct.PLL.PLLR = 2;
     if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
         Error_Handler();
     }
     RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
             | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
     RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
     RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
     RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
     RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
     if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK) {
         Error_Handler();
     }
 }
References __HAL_PWR_VOLTAGESCALING_CONFIG, __HAL_RCC_PWR_CLK_ENABLE, RCC_ClkInitTypeDef::AHBCLKDivider, RCC_ClkInitTypeDef::APB1CLKDivider, RCC_ClkInitTypeDef::APB2CLKDivider, RCC_ClkInitTypeDef::ClockType, Error_Handler(), HAL_OK, HAL_RCC_ClockConfig(), HAL_RCC_OscConfig(), RCC_OscInitTypeDef::HSICalibrationValue, RCC_OscInitTypeDef::HSIState, RCC_OscInitTypeDef::OscillatorType, RCC_OscInitTypeDef::PLL, RCC_PLLInitTypeDef::PLLM, RCC_PLLInitTypeDef::PLLN, RCC_PLLInitTypeDef::PLLP, RCC_PLLInitTypeDef::PLLQ, RCC_PLLInitTypeDef::PLLSource, RCC_PLLInitTypeDef::PLLState, PWR_REGULATOR_VOLTAGE_SCALE3, RCC_CLOCKTYPE_HCLK, RCC_CLOCKTYPE_PCLK1, RCC_CLOCKTYPE_PCLK2, RCC_CLOCKTYPE_SYSCLK, RCC_HCLK_DIV1, RCC_HCLK_DIV2, RCC_HSI_ON, RCC_HSICALIBRATION_DEFAULT, RCC_OSCILLATORTYPE_HSI, RCC_PLL_ON, RCC_PLLP_DIV4, RCC_PLLSOURCE_HSI, RCC_SYSCLK_DIV1, RCC_SYSCLKSOURCE_PLLCLK, and RCC_ClkInitTypeDef::SYSCLKSource.
Referenced by main().
turn_ignition_off()
void turn_ignition_off ()
Emulates ignition shutdown.
Parameters
None
Return values
None.
Definition at line 816 of file main.c.
{
     is_ignition_on = false;
     char txt[] = "Turning Ignition OFF...\n\r";
     HAL_UART_Transmit(&huart2, (const uint8_t*) txt, strlen(txt), 100);
     measurements_count = 0;
     HAL_GPIO_WritePin(GPIOC, GPIO_PIN_9, GPIO_PIN_RESET);
     HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, GPIO_PIN_RESET);
 }
References GPIO_PIN_12, GPIO_PIN_9, GPIO_PIN_RESET, GPIOA, GPIOC, HAL_GPIO_WritePin(), HAL_UART_Transmit(), huart2, is_ignition_on, and measurements_count.
Referenced by turn_vehicle_off().
turn_ignition_on()
void turn_ignition_on ()
Emulates turning on the car ignition.
Parameters
None
Return values
None
Definition at line 156 of file main.c.
{
     is_sleep_detected = false;
     is_ignition_on = true;
     char txt[] = "Turning Ignition ON...\n\r";
     HAL_UART_Transmit(&huart2, (const uint8_t*) txt, strlen(txt), 100);
 }
References HAL_UART_Transmit(), huart2, is_ignition_on, and is_sleep_detected.
Referenced by HAL_GPIO_EXTI_Callback().
turn_vehicle_off()
void turn_vehicle_off ()
Emulates vehicle shutdown.
Parameters
None
Return values
None.
Definition at line 803 of file main.c.
{
     char txt[] = "Turning car OFF...\n\r";
     HAL_UART_Transmit(&huart2, (const uint8_t*) txt, strlen(txt), 100);
     is_car_on = false;
     turn_ignition_off();
 }
References HAL_UART_Transmit(), huart2, is_car_on, and turn_ignition_off().
Referenced by check_sensor_measurements(), driver_asleep(), HAL_GPIO_EXTI_Callback(), and main().
turn_vehicle_on()
void turn_vehicle_on ()
Emulates turning on the car.
Parameters
None
Return values
None
Definition at line 170 of file main.c.
{
     char txt[] = "Turning car ON...\n\r";
     HAL_UART_Transmit(&huart2, (const uint8_t*) txt, strlen(txt), 100);
     is_car_on = true;
 }
References HAL_UART_Transmit(), huart2, and is_car_on.
Referenced by main().
uS_delay()
void uS_delay (uint16_t delay)
Delay function in microseconds.
Parameters
[in] delay The delay time.
Return values
None
Definition at line 242 of file main.c.
{
     __HAL_TIM_SET_COUNTER(&htim1, 0);
     while (__HAL_TIM_GET_COUNTER(&htim1) < delay)
         ;
 }
References __HAL_TIM_GET_COUNTER, __HAL_TIM_SET_COUNTER, and htim1.
Referenced by start_measurement().
verify_sensor_measurements()
void verify_sensor_measurements ()
Verifying the new captured value of all sensors using a "Running Median" algorithm with a given THRESHOLD value, to detect outliers and possible sensor malfunction during runtime.
Parameters
None
Return values
None
Definition at line 420 of file main.c.
{
     switch (measurements_count) {
     case 1:
         window_front_sensor1[0] = floorf(distance_front_sensor1 * 100) / 100;
         window_front_sensor2[0] = floorf(distance_front_sensor2 * 100) / 100;
         window_back_sensor1[0] = floorf(distance_back_sensor1 * 100) / 100;
         window_back_sensor2[0] = floorf(distance_back_sensor2 * 100) / 100;
         break;
     case 2:
         window_front_sensor1[1] = floorf(distance_front_sensor1 * 100) / 100;
         window_front_sensor2[1] = floorf(distance_front_sensor2 * 100) / 100;
         window_back_sensor1[1] = floorf(distance_back_sensor1 * 100) / 100;
         window_back_sensor2[1] = floorf(distance_back_sensor2 * 100) / 100;
         break;
     case 3:
         window_front_sensor1[2] = floorf(distance_front_sensor1 * 100) / 100;
         window_front_sensor2[2] = floorf(distance_front_sensor2 * 100) / 100;
         window_back_sensor1[2] = floorf(distance_back_sensor1 * 100) / 100;
         window_back_sensor2[2] = floorf(distance_back_sensor2 * 100) / 100;
         break;
     default:
         for (int i = 0; i < WINDOW_SIZE - 1; i++) {
             window_front_sensor1[i] = window_front_sensor1[i + 1];
             window_front_sensor2[i] = window_front_sensor2[i + 1];
             window_back_sensor1[i] = window_back_sensor1[i + 1];
             window_back_sensor2[i] = window_back_sensor2[i + 1];
         }
         window_front_sensor1[2] = floorf(distance_front_sensor1 * 100) / 100;
         window_front_sensor2[2] = floorf(distance_front_sensor2 * 100) / 100;
         window_back_sensor1[2] = floorf(distance_back_sensor1 * 100) / 100;
         window_back_sensor2[2] = floorf(distance_back_sensor2 * 100) / 100;
         float median_front_sensor1 = calculate_median(window_front_sensor1);
         float median_front_sensor2 = calculate_median(window_front_sensor2);
         float median_back_sensor1 = calculate_median(window_back_sensor1);
         float median_back_sensor2 = calculate_median(window_back_sensor2);
         if(fabs(window_front_sensor1[2] - median_front_sensor1) > THRESHOLD){
             front_sensor1_strikes +=1;
             window_front_sensor1[2] = median_front_sensor1;
             distance_front_sensor1 = median_front_sensor1;
         }
         else{
             front_sensor1_strikes = 0;
         }
         if(fabs(window_front_sensor2[2] - median_front_sensor2) > THRESHOLD){
             front_sensor2_strikes +=1;
             window_front_sensor2[2] = median_front_sensor2;
             distance_front_sensor2 = median_front_sensor2;
         }
         else{
             front_sensor2_strikes = 0;
         }
         if(fabs(window_back_sensor1[2] - median_back_sensor1) > THRESHOLD){
             back_sensor1_strikes +=1;
             window_back_sensor1[2] = median_back_sensor1;
             distance_back_sensor1 = median_back_sensor1;
         }
         else{
             back_sensor1_strikes = 0;
         }
         if(fabs(window_back_sensor2[2] - median_back_sensor2) > THRESHOLD){
             back_sensor2_strikes +=1;
             window_back_sensor2[2] = median_back_sensor2;
             distance_back_sensor2 = median_back_sensor2;
         }
         else{
             back_sensor2_strikes = 0;
         }
         is_front_sensor1_operative =
                 front_sensor1_strikes < STRIKE_LIMIT ? true : false;
         is_front_sensor2_operative =
                 front_sensor2_strikes < STRIKE_LIMIT ? true : false;
         is_back_sensor1_operative =
                 back_sensor1_strikes < STRIKE_LIMIT ? true : false;
         is_back_sensor2_operative =
                 back_sensor2_strikes < STRIKE_LIMIT ? true : false;
         break;
     }
 }
References back_sensor1_strikes, back_sensor2_strikes, calculate_median(), distance_back_sensor1, distance_back_sensor2, distance_front_sensor1, distance_front_sensor2, front_sensor1_strikes, front_sensor2_strikes, is_back_sensor1_operative, is_back_sensor2_operative, is_front_sensor1_operative, is_front_sensor2_operative, measurements_count, STRIKE_LIMIT, THRESHOLD, window_back_sensor1, window_back_sensor2, window_front_sensor1, window_front_sensor2, and WINDOW_SIZE.
Referenced by main().
Variable Documentation
back_sensor1_strikes
uint8_t back_sensor1_strikes = 0
Definition at line 137 of file main.c.
Referenced by verify_sensor_measurements().
back_sensor2_strikes
uint8_t back_sensor2_strikes = 0
Definition at line 147 of file main.c.
Referenced by verify_sensor_measurements().
difference_back_sensor1
uint32_t difference_back_sensor1 = 0
Definition at line 132 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
difference_back_sensor2
uint32_t difference_back_sensor2 = 0
Definition at line 142 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
difference_front_sensor1
uint32_t difference_front_sensor1 = 0
Definition at line 112 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
difference_front_sensor2
uint32_t difference_front_sensor2 = 0
Definition at line 122 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
distance_back_sensor1
float distance_back_sensor1 = 0
Definition at line 134 of file main.c.
Referenced by check_sensor_measurements(), HAL_TIM_IC_CaptureCallback(), and verify_sensor_measurements().
distance_back_sensor2
float distance_back_sensor2 = 0
Definition at line 144 of file main.c.
Referenced by check_sensor_measurements(), HAL_TIM_IC_CaptureCallback(), and verify_sensor_measurements().
distance_front_sensor1
float distance_front_sensor1 = 0
Definition at line 114 of file main.c.
Referenced by check_sensor_measurements(), HAL_TIM_IC_CaptureCallback(), and verify_sensor_measurements().
distance_front_sensor2
float distance_front_sensor2 = 0
Definition at line 124 of file main.c.
Referenced by check_sensor_measurements(), HAL_TIM_IC_CaptureCallback(), and verify_sensor_measurements().
end_of_pulse_back_sensor1
uint32_t end_of_pulse_back_sensor1 = 0
Definition at line 131 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
end_of_pulse_back_sensor2
uint32_t end_of_pulse_back_sensor2 = 0
Definition at line 141 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
end_of_pulse_front_sensor1
uint32_t end_of_pulse_front_sensor1 = 0
Definition at line 111 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
end_of_pulse_front_sensor2
uint32_t end_of_pulse_front_sensor2 = 0
Definition at line 121 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
final_back_distance
float final_back_distance = 0
Definition at line 107 of file main.c.
Referenced by check_distance_status(), and check_sensor_measurements().
final_front_distance
float final_front_distance = 0
Definition at line 106 of file main.c.
Referenced by check_distance_status(), and check_sensor_measurements().
front_sensor1_strikes
uint8_t front_sensor1_strikes = 0
Definition at line 117 of file main.c.
Referenced by verify_sensor_measurements().
front_sensor2_strikes
uint8_t front_sensor2_strikes = 0
Definition at line 127 of file main.c.
Referenced by verify_sensor_measurements().
htim1
TIM_HandleTypeDef htim1
Definition at line 52 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback(), main(), MX_TIM1_Init(), start_measurement(), TIM1_CC_IRQHandler(), and uS_delay().
htim3
TIM_HandleTypeDef htim3
Definition at line 53 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback(), main(), MX_TIM3_Init(), start_measurement(), and TIM3_IRQHandler().
htim4
TIM_HandleTypeDef htim4
Definition at line 54 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback(), main(), MX_TIM4_Init(), start_measurement(), and TIM4_IRQHandler().
htim8
TIM_HandleTypeDef htim8
Definition at line 55 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback(), main(), MX_TIM8_Init(), start_measurement(), and TIM8_CC_IRQHandler().
huart2
UART_HandleTypeDef huart2
Definition at line 57 of file main.c.
Referenced by check_alcohol_level(), check_distance_status(), check_sensor_measurements(), driver_asleep(), MX_USART2_UART_Init(), turn_ignition_off(), turn_ignition_on(), turn_vehicle_off(), and turn_vehicle_on().
is_back_sensor1_operative
bool is_back_sensor1_operative = true
Definition at line 136 of file main.c.
Referenced by check_sensor_measurements(), start_measurement(), and verify_sensor_measurements().
is_back_sensor2_operative
bool is_back_sensor2_operative = true
Definition at line 146 of file main.c.
Referenced by check_sensor_measurements(), start_measurement(), and verify_sensor_measurements().
is_car_on
bool is_car_on = false
Definition at line 98 of file main.c.
Referenced by main(), turn_vehicle_off(), and turn_vehicle_on().
is_front_sensor1_operative
bool is_front_sensor1_operative = true
Definition at line 116 of file main.c.
Referenced by check_sensor_measurements(), start_measurement(), and verify_sensor_measurements().
is_front_sensor2_operative
bool is_front_sensor2_operative = true
Definition at line 126 of file main.c.
Referenced by check_sensor_measurements(), start_measurement(), and verify_sensor_measurements().
is_ignition_on
bool is_ignition_on = false
Definition at line 99 of file main.c.
Referenced by HAL_GPIO_EXTI_Callback(), main(), turn_ignition_off(), and turn_ignition_on().
is_sleep_detected
bool is_sleep_detected = false
Definition at line 100 of file main.c.
Referenced by check_distance_status(), driver_asleep(), HAL_GPIO_EXTI_Callback(), and turn_ignition_on().
is_start_captured_back_sensor1
bool is_start_captured_back_sensor1 = false
Definition at line 133 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
is_start_captured_back_sensor2
bool is_start_captured_back_sensor2 = false
Definition at line 143 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
is_start_captured_front_sensor1
bool is_start_captured_front_sensor1 = false
Definition at line 113 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
is_start_captured_front_sensor2
bool is_start_captured_front_sensor2 = false
Definition at line 123 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
measurements_count
uint8_t measurements_count = 0
Definition at line 103 of file main.c.
Referenced by start_measurement(), turn_ignition_off(), and verify_sensor_measurements().
oneSec
uint32_t oneSec = 0
Definition at line 101 of file main.c.
Referenced by check_distance_status().
start_of_pulse_back_sensor1
uint32_t start_of_pulse_back_sensor1 = 0
Definition at line 130 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
start_of_pulse_back_sensor2
uint32_t start_of_pulse_back_sensor2 = 0
Definition at line 140 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
start_of_pulse_front_sensor1
uint32_t start_of_pulse_front_sensor1 = 0
Definition at line 110 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
start_of_pulse_front_sensor2
uint32_t start_of_pulse_front_sensor2 = 0
Definition at line 120 of file main.c.
Referenced by HAL_TIM_IC_CaptureCallback().
twoSec
uint32_t twoSec = 0
Definition at line 102 of file main.c.
Referenced by check_distance_status(), and HAL_GPIO_EXTI_Callback().
window_back_sensor1
float window_back_sensor1[WINDOW_SIZE]
Definition at line 135 of file main.c.
Referenced by verify_sensor_measurements().
window_back_sensor2
float window_back_sensor2[WINDOW_SIZE]
Definition at line 145 of file main.c.
Referenced by verify_sensor_measurements().
window_front_sensor1
float window_front_sensor1[WINDOW_SIZE]
Definition at line 115 of file main.c.
Referenced by verify_sensor_measurements().
window_front_sensor2
float window_front_sensor2[WINDOW_SIZE]
Definition at line 125 of file main.c.
Referenced by verify_sensor_measurements().