SoC Advanced: Core/Inc/stm32f4xx_it.h File Reference
stm32f4xx_it.h File Reference
This file contains the headers of the interrupt handlers.
Functions
void NMI_Handler (void)
This function handles Non maskable interrupt.
void HardFault_Handler (void)
This function handles Hard fault interrupt.
void MemManage_Handler (void)
This function handles Memory management fault.
void BusFault_Handler (void)
This function handles Pre-fetch fault, memory access fault.
void UsageFault_Handler (void)
This function handles Undefined instruction or illegal state.
void SVC_Handler (void)
This function handles System service call via SWI instruction.
void DebugMon_Handler (void)
This function handles Debug monitor.
void PendSV_Handler (void)
This function handles Pendable request for system service.
void SysTick_Handler (void)
This function handles System tick timer.
void EXTI9_5_IRQHandler (void)
This function handles EXTI line[9:5] interrupts.
void TIM1_CC_IRQHandler (void)
This function handles TIM1 capture compare interrupt.
void TIM3_IRQHandler (void)
This function handles TIM3 global interrupt.
void TIM4_IRQHandler (void)
This function handles TIM4 global interrupt.
void EXTI15_10_IRQHandler (void)
This function handles EXTI line[15:10] interrupts.
void TIM8_CC_IRQHandler (void)
This function handles TIM8 capture compare interrupt.
Detailed Description
This file contains the headers of the interrupt handlers.
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file stm32f4xx_it.h.
Function Documentation
BusFault_Handler()
void BusFault_Handler (void)
This function handles Pre-fetch fault, memory access fault.
Definition at line 117 of file stm32f4xx_it.c.
 {
   /* USER CODE BEGIN BusFault_IRQn 0 */
   /* USER CODE END BusFault_IRQn 0 */
   while (1)
   {
     /* USER CODE BEGIN W1_BusFault_IRQn 0 */
     /* USER CODE END W1_BusFault_IRQn 0 */
   }
 }
DebugMon_Handler()
void DebugMon_Handler (void)
This function handles Debug monitor.
Definition at line 160 of file stm32f4xx_it.c.
 {
   /* USER CODE BEGIN DebugMonitor_IRQn 0 */
   /* USER CODE END DebugMonitor_IRQn 0 */
   /* USER CODE BEGIN DebugMonitor_IRQn 1 */
   /* USER CODE END DebugMonitor_IRQn 1 */
 }
EXTI15_10_IRQHandler()
void EXTI15_10_IRQHandler (void)
This function handles EXTI line[15:10] interrupts.
Definition at line 263 of file stm32f4xx_it.c.
 {
   /* USER CODE BEGIN EXTI15_10_IRQn 0 */
   /* USER CODE END EXTI15_10_IRQn 0 */
   HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_13);
   /* USER CODE BEGIN EXTI15_10_IRQn 1 */
   /* USER CODE END EXTI15_10_IRQn 1 */
 }
References GPIO_PIN_13, and HAL_GPIO_EXTI_IRQHandler().
EXTI9_5_IRQHandler()
void EXTI9_5_IRQHandler (void)
This function handles EXTI line[9:5] interrupts.
Definition at line 207 of file stm32f4xx_it.c.
 {
   /* USER CODE BEGIN EXTI9_5_IRQn 0 */
   /* USER CODE END EXTI9_5_IRQn 0 */
   HAL_GPIO_EXTI_IRQHandler(GPIO_PIN_7);
   /* USER CODE BEGIN EXTI9_5_IRQn 1 */
   /* USER CODE END EXTI9_5_IRQn 1 */
 }
References GPIO_PIN_7, and HAL_GPIO_EXTI_IRQHandler().
HardFault_Handler()
void HardFault_Handler (void)
This function handles Hard fault interrupt.
Definition at line 87 of file stm32f4xx_it.c.
 {
   /* USER CODE BEGIN HardFault_IRQn 0 */
   /* USER CODE END HardFault_IRQn 0 */
   while (1)
   {
     /* USER CODE BEGIN W1_HardFault_IRQn 0 */
     /* USER CODE END W1_HardFault_IRQn 0 */
   }
 }
MemManage_Handler()
void MemManage_Handler (void)
This function handles Memory management fault.
Definition at line 102 of file stm32f4xx_it.c.
 {
   /* USER CODE BEGIN MemoryManagement_IRQn 0 */
   /* USER CODE END MemoryManagement_IRQn 0 */
   while (1)
   {
     /* USER CODE BEGIN W1_MemoryManagement_IRQn 0 */
     /* USER CODE END W1_MemoryManagement_IRQn 0 */
   }
 }
NMI_Handler()
void NMI_Handler (void)
This function handles Non maskable interrupt.
Definition at line 72 of file stm32f4xx_it.c.
 {
   /* USER CODE BEGIN NonMaskableInt_IRQn 0 */
   /* USER CODE END NonMaskableInt_IRQn 0 */
   /* USER CODE BEGIN NonMaskableInt_IRQn 1 */
   while (1)
   {
   }
   /* USER CODE END NonMaskableInt_IRQn 1 */
 }
PendSV_Handler()
void PendSV_Handler (void)
This function handles Pendable request for system service.
Definition at line 173 of file stm32f4xx_it.c.
 {
   /* USER CODE BEGIN PendSV_IRQn 0 */
   /* USER CODE END PendSV_IRQn 0 */
   /* USER CODE BEGIN PendSV_IRQn 1 */
   /* USER CODE END PendSV_IRQn 1 */
 }
SVC_Handler()
void SVC_Handler (void)
This function handles System service call via SWI instruction.
Definition at line 147 of file stm32f4xx_it.c.
 {
   /* USER CODE BEGIN SVCall_IRQn 0 */
   /* USER CODE END SVCall_IRQn 0 */
   /* USER CODE BEGIN SVCall_IRQn 1 */
   /* USER CODE END SVCall_IRQn 1 */
 }
SysTick_Handler()
void SysTick_Handler (void)
This function handles System tick timer.
Definition at line 186 of file stm32f4xx_it.c.
 {
   /* USER CODE BEGIN SysTick_IRQn 0 */
   /* USER CODE END SysTick_IRQn 0 */
   HAL_IncTick();
   /* USER CODE BEGIN SysTick_IRQn 1 */
   /* USER CODE END SysTick_IRQn 1 */
 }
References HAL_IncTick().
TIM1_CC_IRQHandler()
void TIM1_CC_IRQHandler (void)
This function handles TIM1 capture compare interrupt.
Definition at line 221 of file stm32f4xx_it.c.
 {
   /* USER CODE BEGIN TIM1_CC_IRQn 0 */
   /* USER CODE END TIM1_CC_IRQn 0 */
   HAL_TIM_IRQHandler(&htim1);
   /* USER CODE BEGIN TIM1_CC_IRQn 1 */
   /* USER CODE END TIM1_CC_IRQn 1 */
 }
References HAL_TIM_IRQHandler(), and htim1.
TIM3_IRQHandler()
void TIM3_IRQHandler (void)
This function handles TIM3 global interrupt.
Definition at line 235 of file stm32f4xx_it.c.
 {
   /* USER CODE BEGIN TIM3_IRQn 0 */
   /* USER CODE END TIM3_IRQn 0 */
   HAL_TIM_IRQHandler(&htim3);
   /* USER CODE BEGIN TIM3_IRQn 1 */
   /* USER CODE END TIM3_IRQn 1 */
 }
References HAL_TIM_IRQHandler(), and htim3.
TIM4_IRQHandler()
void TIM4_IRQHandler (void)
This function handles TIM4 global interrupt.
Definition at line 249 of file stm32f4xx_it.c.
 {
   /* USER CODE BEGIN TIM4_IRQn 0 */
   /* USER CODE END TIM4_IRQn 0 */
   HAL_TIM_IRQHandler(&htim4);
   /* USER CODE BEGIN TIM4_IRQn 1 */
   /* USER CODE END TIM4_IRQn 1 */
 }
References HAL_TIM_IRQHandler(), and htim4.
TIM8_CC_IRQHandler()
void TIM8_CC_IRQHandler (void)
This function handles TIM8 capture compare interrupt.
Definition at line 277 of file stm32f4xx_it.c.
 {
   /* USER CODE BEGIN TIM8_CC_IRQn 0 */
   /* USER CODE END TIM8_CC_IRQn 0 */
   HAL_TIM_IRQHandler(&htim8);
   /* USER CODE BEGIN TIM8_CC_IRQn 1 */
   /* USER CODE END TIM8_CC_IRQn 1 */
 }
References HAL_TIM_IRQHandler(), and htim8.
UsageFault_Handler()
void UsageFault_Handler (void)
This function handles Undefined instruction or illegal state.
Definition at line 132 of file stm32f4xx_it.c.
 {
   /* USER CODE BEGIN UsageFault_IRQn 0 */
   /* USER CODE END UsageFault_IRQn 0 */
   while (1)
   {
     /* USER CODE BEGIN W1_UsageFault_IRQn 0 */
     /* USER CODE END W1_UsageFault_IRQn 0 */
   }
 }